# site settings
title: Immersive Expressions
organization: ACM SIGGRAPH
organization_url: http://www.siggraph.org
parent: Digital Arts Community
parent_url: http://www.siggraph.org/connect/digital-arts
email: dostrenko@siggraph.org
description: An online digital art exhibition showcasing virtual reality on the web.

# baseurl: "/~dostrenko/private/webvrshow_exhibit/_site" # the subpath of your site, e.g. /blog
# url: "http://127.0.0.1:4001" # the base hostname & protocol for your site

defaults:
  -
    scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: "assets/css"
    values:
      stylesheet: true
  -
    scope:
      path: "assets/js"
    values:
      javascript: true

collections:
  works:
    output: true
    # permalink: :name

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 18

# build settings
markdown: kramdown

sass:
  style: compressed

exclude: [Guardfile, LICENSE.md, 'README.md', 'Gemfile.lock', 'Gemfile', CONTRIBUTING.md, forty_jekyll_theme.gemspec]
